version: '3.8'

services:
  db-inventario:
    image: postgres:15
    container_name: postgres-inventario
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersayayin21
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: