spring.application.name=invent-api
# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario_db
spring.datasource.username=admin
spring.datasource.password=supersayayin21
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: Crea las tablas automáticamente basado en tu Entidad Producto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true