spring.application.name=invent-api

# Conexión a PostgreSQL usando Variables de Entorno
# Formato: ${NOMBRE_VARIABLE:VALOR_POR_DEFECTO}
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:inventario_db}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true